### ISSUE TITLE
Add readme template

### ISSUE THREAD

**Issue by trong-le** [aries-data/generator-aries-activity#12]
Copy readme template from [phabricator](http://phabricator.astronomer.io/w/public/how-to/build-integration/aries/readme/)

**Comment by benjamingregory** [comment]
Done

**Comment by benjamingregory** [comment]
@perryao The markdown for the readme is here:

http://phabricator.astronomer.io/w/public/how-to/build-integration/aries/readme/

Should we include as boilerplate Readme?

**Comment by ryw** [comment]
no more work on aries
