### ISSUE TITLE
Add enrichment option to activity type question

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/generator-aries-activity#13]
### Do you want to request a feature or report a bug?
Feature Request
### What is the current behavior?
You can only create a source, sink, or transform. Enrichments like ip address lookups do not currently fit nicely in this naming convention.
### If the current behavior is a bug, please provide the steps to reproduce.
N/A
### What is the expected behavior?
In the question re: activity type, enrichment is given as an option.
### Which versions of generator-aries-activity, and which Node versions are affected by this issue? Did this work in previous versions of generator-aries-activity?
N/A

**Comment by ryw** [comment]
no more work on aries
