### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by trong-le** [aries-data/generator-aries-activity#8]
- [ ] Remove blue-tape
- [ ] Add mocha testing
- [ ] Add mocha testing dependencies

See [CSV to JSON test](https://github.com/aries-data/aries-activity-csv-to-json/blob/master/test/test.js) for examples of test case. and [dependencies in package.json](https://github.com/aries-data/aries-activity-csv-to-json/blob/master/package.json) for dependencies needed.

**Comment by perryao** [comment]
this should be complete as a result of #10. @trong-le can you confirm later?

**Comment by trong-le** [comment]
@perryao yeah that fixes this. I'll close this one out.
